services:
  # Backend API
  - type: web
    name: mundial2026-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_URL_SYNC
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://mundial-2026-ui.onrender.com # Cambiar por el dominio final del frontend
      - key: FOOTBALL_API_KEY
        sync: false

  # Frontend Static Site
  - type: web
    name: mundial2026-ui
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: mundial2026-api
          property: host
    staticPublishCustomHeaders:
      - path: "/*"
        headers:
          - key: "Cache-Control"
            value: "no-cache"
