"""add_bracket_config

Revision ID: 469247e11dc1
Revises: 4ee31c2789c5
Create Date: 2026-05-03 01:17:27.076945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469247e11dc1'
down_revision: Union[str, Sequence[str], None] = '4ee31c2789c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polla_config', sa.Column('is_bracket_open', sa.Boolean(), nullable=False))
    op.add_column('polla_config', sa.Column('points_bracket_r16', sa.Integer(), nullable=False))
    op.add_column('polla_config', sa.Column('points_bracket_qf', sa.Integer(), nullable=False))
    op.add_column('polla_config', sa.Column('points_bracket_sf', sa.Integer(), nullable=False))
    op.add_column('polla_config', sa.Column('points_bracket_final', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polla_config', 'points_bracket_final')
    op.drop_column('polla_config', 'points_bracket_sf')
    op.drop_column('polla_config', 'points_bracket_qf')
    op.drop_column('polla_config', 'points_bracket_r16')
    op.drop_column('polla_config', 'is_bracket_open')
    # ### end Alembic commands ###
