"""add_external_id_to_team

Revision ID: 730253087830
Revises: 22a449cc7634
Create Date: 2026-04-29 00:04:36.922016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730253087830'
down_revision: Union[str, Sequence[str], None] = '22a449cc7634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('external_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_teams_external_id'), 'teams', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_external_id'), table_name='teams')
    op.drop_column('teams', 'external_id')
    # ### end Alembic commands ###
